version: "3"


services:

  airline-backend-service:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - DB_URL_ARG=jdbc:postgresql://airline-database-service:5432/airline
        - DB_USER_ARG=abhinn
        - DB_PASS_ARG=sarkar

    image: airline-backend-dev
    container_name: airline-backend-service-dev

    ports:
      - "80:8080"
